name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GO111MODULE: on

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.11, 1.12, 1.13, 1.14]
    name: ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Set GOPATH and PATH
        run: |
          echo "::set-env name=GOPATH::$(dirname $GITHUB_WORKSPACE)"
          echo "::add-path::$(dirname $GITHUB_WORKSPACE)/bin"
        shell: bash

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Checkout Code
        uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}

      - name: Install Dependencies
        run: go get -v golang.org/x/lint/golint

      - name: Run Tests
        run: |
          golint -set_exit_status ./...
          go test -race --coverprofile=coverage.coverprofile --covermode=atomic ./...
      - name: Upload coverage to Codecov
        if: success() && matrix.go == 1.13 && matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v1
        with:
          token:
          fail_ci_if_error: false

  release:
    name: Release
    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/main'
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx -p @semantic-release/changelog -p @semantic-release/git -p semantic-release semantic-release -d --debug
